### ISSUE TITLE
Local.xml staat public + website naam: http://www.kokettekatinka.be/

### ISSUE THREAD

**Issue by Luciferiix** [gertst/koket#1]
Je site is down en waarschijnlijk gehacked.

http://www.kokettekatinka.be/

Verder heb je modules die betaald zijn publiek op het internet gezet.

Groeten: Roger

**Comment by gertst** [comment]
Die login data is enkel van de locale test server hoor, en daarna in .gitignore gezet zodat er nooit info van de live server kon staan.

De site is al een jaar niet meer in gebruik en dus niet gehacked.

Maar zeker bedankt voor de info: much appreciated!

**Comment by Luciferiix** [comment]
Prima !

Heb een zoek machine gemaakt die GitHub afgaat voor Maganto 1 modules en websites.
Ben op het idee gekomen van iemand die het zelfde doet maar dan met bitcoin adressen en ssh sleutels in GIT ;-)
